services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '5432:5432'
    volumes:
      - data-postgres:/var/lib/postgresql/data

#  cryptopulse:
#    build: .
##    image: cryptopulse:latest
#    command: python run.py
#    env_file:
#      - .env
#    restart: unless-stopped
#    depends_on:
#      - postgres

volumes:
  data-postgres:
