"""add гÑr_coins and candles tables

Revision ID: 88a779891cbc
Revises: 6617b6250294
Create Date: 2025-12-09 19:02:34.868374

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "88a779891cbc"
down_revision: str | Sequence[str] | None = "6617b6250294"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
