"""add tariff_plan foreign keys

Revision ID: 939a984fbdd9
Revises: 7a9e6df75c7d
Create Date: 2026-01-08 16:10:26.947795

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "939a984fbdd9"
down_revision: Union[str, Sequence[str], None] = "7a9e6df75c7d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1) добавляем колонки ВРЕМЕННО nullable=True
    op.add_column("users", sa.Column("tariff_plan_id", sa.Integer(), nullable=True))
    op.add_column("payments", sa.Column("tariff_plan_id", sa.Integer(), nullable=True))

    # 2) заполняем users.tariff_plan_id по старому users.tariff_code
    # (tariff_code enum -> text через ::text)
    op.execute(
        """
        UPDATE users u
        SET tariff_plan_id = tp.id
        FROM tariff_plans tp
        WHERE tp.code = u.tariff_code::text
          AND u.tariff_plan_id IS NULL
    """
    )

    # 3) заполняем payments.tariff_plan_id по старому payments.tariff_code
    op.execute(
        """
        UPDATE payments p
        SET tariff_plan_id = tp.id
        FROM tariff_plans tp
        WHERE tp.code = p.tariff_code::text
          AND p.tariff_plan_id IS NULL
    """
    )

    # 4) защита на случай если где-то вдруг NULL остался: ставим free
    op.execute(
        """
        UPDATE users
        SET tariff_plan_id = (SELECT id FROM tariff_plans WHERE code = 'free' LIMIT 1)
        WHERE tariff_plan_id IS NULL
    """
    )
    op.execute(
        """
        UPDATE payments
        SET tariff_plan_id = (SELECT id FROM tariff_plans WHERE code = 'free' LIMIT 1)
        WHERE tariff_plan_id IS NULL
    """
    )

    # 5) теперь можно сделать NOT NULL
    op.alter_column("users", "tariff_plan_id", nullable=False)
    op.alter_column("payments", "tariff_plan_id", nullable=False)

    # 6) индексы + FK
    op.create_index(op.f("ix_users_tariff_plan_id"), "users", ["tariff_plan_id"], unique=False)
    op.create_index(
        op.f("ix_payments_tariff_plan_id"), "payments", ["tariff_plan_id"], unique=False
    )

    op.create_foreign_key(
        "fk_users_tariff_plan_id",
        "users",
        "tariff_plans",
        ["tariff_plan_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_payments_tariff_plan_id",
        "payments",
        "tariff_plans",
        ["tariff_plan_id"],
        ["id"],
        ondelete="RESTRICT",
    )

    # 7) только теперь удаляем старые колонки
    op.drop_column("users", "tariff_code")
    op.drop_column("payments", "tariff_code")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "tariff_code",
            postgresql.ENUM("free", "paid_month", "paid_year", name="tariff_code"),
            server_default=sa.text("'free'::tariff_code"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_index(op.f("ix_users_tariff_plan_id"), table_name="users")
    op.drop_column("users", "tariff_plan_id")
    op.add_column(
        "payments",
        sa.Column(
            "tariff_code",
            postgresql.ENUM("free", "paid_month", "paid_year", name="tariff_code"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "payments", type_="foreignkey")
    op.drop_index(op.f("ix_payments_tariff_plan_id"), table_name="payments")
    op.drop_column("payments", "tariff_plan_id")
    # ### end Alembic commands ###
