"""Make direction nullable

Revision ID: f57465a161f2
Revises: f37af3feb2bc
Create Date: 2025-07-25 13:57:56.619196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f57465a161f2'
down_revision: Union[str, Sequence[str], None] = 'f37af3feb2bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'direction',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'direction',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
